<?php
$urlBase = $this->getBaseUrl();
$currentCategoryName = $this->getCurrentCategory()->getName();
$currentCurrencyCode = $this->getCurrentCurrencyCode();
$grandTotal = $this->getGrandTotalInCart();
?>
<script type="text/javascript">
    require(['jquery'], function($) {
        $(document).ready(function() {
            $(".action.tocart.tiktok-pixel.primary").click(function() {
                //TikTok Pixel Code
                let product_id = ($(this).siblings('[name="product"]').val());
                $.ajax({
                    type: "POST",
                    url: "<?= $urlBase ?>tiktokpixel/product/data",
                    data: {
                        'product_id': product_id,
                    },
                    dataType: 'json',
                    success: function(response) {
                        // TikTok Pixel Code
                        let value = parseInt(response.procut_price) + parseInt(<?= number_format($grandTotal, 2, '.', $thousands_sep = ',') ?>);
                        ttq.track('AddToCart',{  
                            content_id: [response.product_id],
                            quantity: 1,
                            price: response.procut_price,
                            value: value,
                            currency: "<?= $currentCurrencyCode ?>",
                        })
                        // End TikTok Pixel Code
                    }
                });
                // End TikTok Pixel Code
            });
        });
    });
</script>